name: handoff_notes
description: Follow-ups & handover notes, offline.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  material_color_utilities: any
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.1
  path: ^1.8.3
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  flutter_local_notifications: ^17.0.0
  uuid: ^4.2.2
  intl: any
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
